version: '3.7'
services:
  nginx:
    build: ./frontend
    ports:
      - '80:80'
    networks:
      - backend
  node:
    build: ./backend
    container_name: 'app-node'
    networks:
      - backend
networks:
  backend:
    name: app_backend
